In [15]:
z = np.array([[1,'A',9.8],[2,'B',10.3]])
print(z)
print(type(z))
print(z.shape)

[['1' 'A' '9.8']
 ['2' 'B' '10.3']]
<class 'numpy.ndarray'>
(2, 3)


In [1]:
#Import numpy library
import numpy as np

In [9]:
#Create 1D numpy array
x = np.array([43,67,57,96])
print(x)
print(type(x))
print(x.dtype)

[43 67 57 96]
<class 'numpy.ndarray'>
int32


In [11]:
#Create 1D numpy array
x = np.array([43,67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

[43.  67.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [13]:
#Create 1D numpy array
x = np.array(["A",43,67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '43' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [15]:
#Create 2D numpy array
y = np.array([[40,67],[57,90]])
print(y)
print(type(y))
print(y.shape)

[[40 67]
 [57 90]]
<class 'numpy.ndarray'>
(2, 2)


In [21]:
c = np.arange(3, 10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [23]:
c = np.arange(-3, 10)
print(c)
type(c)

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]


numpy.ndarray

In [25]:
d = np.array([1.3467, 3.10987, 4.85756])
print(d)
np.around(d, 2)

[1.3467  3.10987 4.85756]


array([1.35, 3.11, 4.86])

In [27]:
d = np.array([1.3467, 3.10987, 4.85756])
print(d)
print(np.around(np.sqrt(d), 2))

[1.3467  3.10987 4.85756]
[1.16 1.76 2.2 ]


In [31]:
a1 = np.array([[3,4,5,6],[7,8,9,2,np.NAN]])
print(a1)
print(a1.shape)
print(a1.dtype)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [33]:
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [35]:
#Matrix Operations
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [59]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.matmul(A, B)
print(C)
print(A. T)
print(B. T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [62]:
a4 = np.array([[3,4,5],[6,7,8],[8,9,7],[36,89,8]])
a4

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 8,  9,  7],
       [36, 89,  8]])

In [64]:
print(a4[1][1])

7
